export type NavSection = "inbox" | "mine" | "unassigned" | "followups" | "resolved" | "analytics" | "settings";

export type {
  AISuggestion,
  AISettings,
  AnalyticsKPI,
  ChannelConnection,
  ChannelType,
  Contact,
  ContactStatus,
  Conversation,
  ConversationDataPoint,
  ConversationDoc,
  ConversationStatus,
  FollowUp,
  FollowUpStatus,
  FollowUpType,
  Message,
  MessageDirection,
  Platform,
  PlatformStat,
  ProductInterest,
  User,
  UserRole,
} from "@core/contracts";
